apiVersion: v1
kind: ConfigMap
metadata:
  name: minion-config
  namespace: minion
data:
  minion-name: minion
  prod: "false"
  http-server-host: 0.0.0.0
  http-server-port: "9000"
  cache-max-keys: "64"
  cache-max-cost: "1000000"
  jaeger-endpoint: http://localhost:14268/api/traces
  amqp-uri: amqp://guest:guest@localhost:5672
