apiVersion: apps/v1
kind: Deployment
metadata:
  name: minion
  namespace: minion
  labels:
    app: minion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minion
  template:
    metadata:
      labels:
        app: minion
    spec:
      containers:
        - name: minion
          image: julesmike/minion
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 9000
          env:
            - name: MINION_KEY
              valueFrom:
                secretKeyRef:
                  name: minion-secret
                  key: minion-key
                  optional: false
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: minion-config
                  key: service-name
            - name: PROD
              valueFrom:
                configMapKeyRef:
                  name: minion-config
                  key: prod
            - name: SPOTIFY_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: minion-config
                  key: spotify-redirect-uri
            - name: HTTP_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: minion-config
                  key: http-server-host
            - name: HTTP_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: minion-config
                  key: http-server-port
            - name: CACHE_MAX_KEYS
              valueFrom:
                configMapKeyRef:
                  name: minion-config
                  key: cache-max-keys
            - name: CACHE_MAX_COST
              valueFrom:
                configMapKeyRef:
                  name: minion-config
                  key: cache-max-cost
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: minion-config
                  key: jaeger-endpoint
            - name: AMQP_URI
              valueFrom:
                configMapKeyRef:
                  name: minion-config
                  key: amqp-uri
