// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: words/words.proto

package words

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WordsServiceClient is the client API for WordsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WordsServiceClient interface {
	AddWord(ctx context.Context, in *AddWordRequest, opts ...grpc.CallOption) (*AddWordResponse, error)
	RandomWord(ctx context.Context, in *RandomWordRequest, opts ...grpc.CallOption) (*RandomWordResponse, error)
	SearchWord(ctx context.Context, in *SearchWordRequest, opts ...grpc.CallOption) (*SearchWordResponse, error)
}

type wordsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWordsServiceClient(cc grpc.ClientConnInterface) WordsServiceClient {
	return &wordsServiceClient{cc}
}

func (c *wordsServiceClient) AddWord(ctx context.Context, in *AddWordRequest, opts ...grpc.CallOption) (*AddWordResponse, error) {
	out := new(AddWordResponse)
	err := c.cc.Invoke(ctx, "/words.WordsService/AddWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordsServiceClient) RandomWord(ctx context.Context, in *RandomWordRequest, opts ...grpc.CallOption) (*RandomWordResponse, error) {
	out := new(RandomWordResponse)
	err := c.cc.Invoke(ctx, "/words.WordsService/RandomWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordsServiceClient) SearchWord(ctx context.Context, in *SearchWordRequest, opts ...grpc.CallOption) (*SearchWordResponse, error) {
	out := new(SearchWordResponse)
	err := c.cc.Invoke(ctx, "/words.WordsService/SearchWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordsServiceServer is the server API for WordsService service.
// All implementations should embed UnimplementedWordsServiceServer
// for forward compatibility
type WordsServiceServer interface {
	AddWord(context.Context, *AddWordRequest) (*AddWordResponse, error)
	RandomWord(context.Context, *RandomWordRequest) (*RandomWordResponse, error)
	SearchWord(context.Context, *SearchWordRequest) (*SearchWordResponse, error)
}

// UnimplementedWordsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWordsServiceServer struct {
}

func (UnimplementedWordsServiceServer) AddWord(context.Context, *AddWordRequest) (*AddWordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWord not implemented")
}
func (UnimplementedWordsServiceServer) RandomWord(context.Context, *RandomWordRequest) (*RandomWordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomWord not implemented")
}
func (UnimplementedWordsServiceServer) SearchWord(context.Context, *SearchWordRequest) (*SearchWordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchWord not implemented")
}

// UnsafeWordsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WordsServiceServer will
// result in compilation errors.
type UnsafeWordsServiceServer interface {
	mustEmbedUnimplementedWordsServiceServer()
}

func RegisterWordsServiceServer(s grpc.ServiceRegistrar, srv WordsServiceServer) {
	s.RegisterService(&WordsService_ServiceDesc, srv)
}

func _WordsService_AddWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordsServiceServer).AddWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/words.WordsService/AddWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordsServiceServer).AddWord(ctx, req.(*AddWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordsService_RandomWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordsServiceServer).RandomWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/words.WordsService/RandomWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordsServiceServer).RandomWord(ctx, req.(*RandomWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordsService_SearchWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordsServiceServer).SearchWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/words.WordsService/SearchWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordsServiceServer).SearchWord(ctx, req.(*SearchWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WordsService_ServiceDesc is the grpc.ServiceDesc for WordsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WordsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "words.WordsService",
	HandlerType: (*WordsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWord",
			Handler:    _WordsService_AddWord_Handler,
		},
		{
			MethodName: "RandomWord",
			Handler:    _WordsService_RandomWord_Handler,
		},
		{
			MethodName: "SearchWord",
			Handler:    _WordsService_SearchWord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "words/words.proto",
}
